LibraryMvc/Models/issuebook.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class issuebook
    {
        public int Id { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string BookName { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    }
}

LibraryMvc/Controllers/IssueBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryMvc.Models;
namespace LibraryMvc.Controllers
{
    public class IssueBookController : Controller
    {

        MVCModel db = new MVCModel();
        // GET: IssueBook
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetMid(int mid)
        {


            var memberid = (from s in db.members where s.Id == mid select s.Name).ToList();

            return Json(memberid,JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult GetBook()
        {


            var books = db.books.Select(p=>new { 
                Id = p.Id,
                Bname = p.BookName
            
            }).ToList();

            return Json(books, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult Save(issuebook issue)
        {
            if (ModelState.IsValid) 
            {
                db.issuebooks.Add(issue);
                db.SaveChanges();
                TempData["SuccessMessage"] = "Added to the database";
                return RedirectToAction("Index");
            }
            return View(issue);
            
            
        }
    }
}

LibraryMvc/Views/IssueBook/Index.cshtml
<div>
    <h3>Issue Book</h3>
</div>
<div class="row form-body">
    <div class="col-sm-4">
        @using (Html.BeginForm("Save", "IssueBook", FormMethod.Post))
        {

            <div class="form-group">
                <label> Member Id</label>
                <input type="text" id="MemberId" name="MemberId" class="form-control" placeholder="Member Id" required />
            </div>

            <div class="form-group">
                <label> Member Name</label>
                <input type="text" id="mname" name="mname" class="form-control" placeholder="Member Name" required />
            </div>

            <div class="form-group">
                <label> Book</label>
                <select class="form-control" id="BookName" name="BookName">
                    <option>Please Select</option>
                </select>
            </div>

            <div class="form-group">
                <label> Issue Date</label>
                <input type="date" id="IssueDate" name="IssueDate" class="form-control" required />
            </div>

            <div class="form-group">
                <label> Return Date</label>
                <input type="date" id="ReturnDate" name="ReturnDate" class="form-control" required />
            </div>

            <div class="form-group">

                <input type="submit" value="Save" class="btn btn-success" required />
            </div>

        }
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '') {
                alertify.success(successMessage)
            }
        })

        getMid()
        getBooks()
        function getMid() {

            $("#MemberId").keyup(function (e) {
                $.ajax({
                    type: 'POST',
                    url: '/IssueBook/GetMid?mid=' + $("#MemberId").val(),
                    dataType: 'JSON',
                    success: function (data) {
                        $("#mname").val(data);
                    }

                });
            });
        }


        function getBooks()
        {
            $.ajax({
                type: 'GET',
                url: '/IssueBook/GetBook',
                dataType: 'JSON',
                success: function (data)
                {
                    console.log(data);

                    for (var i = 0; i < data.length; i++)
                    {
                        $('#BookName').append($("<option/>",
                            {
                                text: data[i].Bname
                            }));
                    }
                },
                error: function (xhr,status,error)
                {
                    alert(xhr.responseText);
                }
            });

        }


    </script>



}